language: node_js
node_js:
  - "node"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - DB_NAME=boardcamp
    - DB_USER=dbowner
    - DB_PASSWORD=dbpassword
before_script:
  - psql -c 'CREATE DATABASE boardcamp;' -U postgres
  - psql --dbname=boardcamp --file=psql_scripts/scripts/create-tables.sql -U postgres
  - cd server
install:
  - yarn install
cache:
  directories:
    - "node_modules"
